name: news_app
description: "A new Flutter project."
generate: true

# Flutter version and environment
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"

# Flutter dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  bloc: ^8.1.4
  shimmer: ^2.0.0 
  cached_network_image: ^3.2.3
  url_launcher: ^6.1.7
  webview_flutter: ^4.0.0 
  intl: ^0.19.0
  google_fonts: ^6.2.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  http: ^1.2.2

# Flutter localization generation
flutter:
  uses-material-design: true
  generate: true
  
flutter_intl:
  enabled: true
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
  output-class: AppLocalizations
  synthetic-package: true
  locales:
    - en
    - es
    - ar
    - fr
  use-deferred-loading: false
  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/


  
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #